openapi: 3.1.1
info:
  title: Movie REST microservice
  summary: API of the Movie service
  description: Updated OpenAPI documentation matching the actual implementation.
  contact:
    name: Helene Coullon
    url: https://helene-coullon.fr/
    email: helene.coullon@imt-atlantique.fr
  license:
    name: GPL v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 1.1.0

tags:
  - name: admins
    description: Admin-only calls (require ?uid=<adminId>)
  - name: developers
    description: Public developer endpoints

paths:
  /:
    get:
      tags: [developers]
      summary: Home page
      operationId: home
      responses:
        "200":
          description: Welcome message
          content:
            text/html:
              schema:
                type: string
                example: <h1 style='color:blue'>Welcome to the Movie service!</h1>

  /movies:
    get:
      tags: [developers]
      summary: Get all movies
      operationId: get_movies
      responses:
        "200":
          description: List of movies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovieItem'

  /movies/{movieid}:
    get:
      tags: [developers]
      summary: Get movie by ID
      operationId: get_movie
      parameters:
        - name: movieid
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Movie found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieItem'
        "404":
          description: Movie not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      tags: [admins]
      summary: Add movie
      operationId: add_movie
      parameters:
        - name: movieid
          in: path
          required: true
          schema:
            type: string
        - name: uid
          in: query
          description: Admin identifier
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovieItem'
      responses:
        "200":
          description: Movie successfully added
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: movie added
        "403":
          description: Unauthorized (not admin)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Movie ID already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      tags: [admins]
      summary: Update a movie rating and title
      operationId: update_movie_rating
      parameters:
        - name: movieid
          in: path
          required: true
          schema:
            type: string
        - name: uid
          in: query
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                rating:
                  type: number
                  example: 8.5
                title:
                  type: string
                  example: New Movie Title
      responses:
        "200":
          description: Movie updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieItem'
        "403":
          description: Unauthorized (not admin)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Movie ID not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      tags: [admins]
      summary: Delete a movie
      operationId: delete_movie
      parameters:
        - name: movieid
          in: path
          required: true
          schema:
            type: string
        - name: uid
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Movie deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieItem'
        "403":
          description: Unauthorized (not admin)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Movie ID not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /moviesbytitle:
    get:
      tags: [developers]
      summary: Get movie by title
      operationId: get_movie_bytitle
      parameters:
        - name: title
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Movie found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieItem'
        "500":
          description: Movie title not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    MovieItem:
      type: object
      required: [id, title, director, rating]
      properties:
        id:
          type: string
          example: 720d006c-3a57-4b6a-b18f-9b713b073f3c
        title:
          type: string
          example: The Martian
        director:
          type: string
          example: Ridley Scott
        rating:
          type: number
          example: 7.5

    Error:
      type: object
      properties:
        error:
          type: string
          example: Movie not found
